cxx_library(
  name = 'libovrplatform_headers',
  header_namespace = '',
  exported_headers = glob([
    ('*.h'),
  ]),
  soname = 'libovrplatform_headers.so',
  compiler_flags = [
    '-O0',
    '-Werror',
    '-fvisibility=default', # For ease of debugging
    '-Wno-unused-variable',
    '-UNDEBUG',
  ],
  linker_flags = [
    '-llog'
  ],
  supported_platforms_regex = "^android-(armv7|x86)$",
  visibility=['PUBLIC'],
)
